# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  # By default, run when update to main.
  push:
    branches: ['main', 'maintenance']
  pull_request:
    branches: ['main', 'maintenance']

  # Make code-review manually runnable.
  workflow_dispatch:

  # Allow to run on schedule.
  schedule:
    - cron: '0 0 * * *'

jobs:
  review:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto-review via Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Opt for i and not ci to detect module updates.
      - run: npm install
      - run: npm run review

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: KemingHe/template-ts-cucumber-setup
    
